basic:
    name: 'EW-FORMS (previously HSQ)'
    environments:
        production: 'https://ecowatch.allstarpros.com/'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /ms_widget_builder/ew-get-gutter-quotes
        - /ms_widget_builder/ew-get-hvac-quotes
        - /ms_widget_builder/ew-get-lawn-care-quotes
        - /ms_widget_builder/ew-get-roofing-quotes
        - /ms_widget_builder/ew-get-solar-quotes
        - /ms_widget_builder/ew-get-window-quotes
    monitoring:
        days: [Sun]
        type: weekly
        schedule_time: '10:30 PM'
        schedule_time_zone: America/New_York
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
